## [作業重點]
目前你應該已經要很清楚資料集中，資料的型態是什麼樣子囉！包含特徵 (features) 與標籤 (labels)。因此要記得未來不管什麼專案，必須要把資料清理成相同的格式，才能送進模型訓練。
今天的作業開始踏入決策樹這個非常重要的模型，請務必確保你理解模型中每個超參數的意思，並試著調整看看，對最終預測結果的影響為何

## 作業

1. 試著調整 DecisionTreeClassifier(...) 中的參數，並觀察是否會改變結果？
2. 改用其他資料集 (boston, wine)，並與回歸模型的結果進行比較

In [2]:
from sklearn import datasets, metrics
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.model_selection import train_test_split

In [6]:
wine = datasets.load_wine()
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=11)
clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acc = metrics.accuracy_score(y_test, y_pred)
print("Acuuracy: ", acc)
print(wine.feature_names)
print("Feature importance: ")
print(clf.feature_importances_)

Acuuracy:  0.9722222222222222
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.01894944 0.         0.         0.         0.         0.03654535
 0.41569866 0.         0.         0.40449822 0.         0.
 0.12430833]


In [18]:
criterion = ['gini', 'entropy']
splitter = ['best', 'random']
max_depth = [2,5,7]
min_samples_split= [5, 10, 20]
min_samples_leaf = [5, 10, 15]
min_weight_fraction_leaf=0.3
best_auc = 0
for a in range(len(criterion)):
    for b in range(len(splitter)):
        for c in range(len(max_depth)):
            for d in range(len(min_samples_split)):
                for e in range(len(min_samples_leaf)):
                    print(criterion[a],splitter[b],max_depth[c],min_samples_split[d],min_samples_leaf[e],min_weight_fraction_leaf)
                    clf = DecisionTreeClassifier(
                    criterion = criterion[a]
                    ,splitter = splitter[b]
                    ,max_depth = max_depth[c]
                    ,min_samples_split = min_samples_split[d]
                    ,min_samples_leaf = min_samples_leaf[e]
                    ,min_weight_fraction_leaf = min_weight_fraction_leaf)
                    clf.fit(x_train, y_train)
                    y_pred = clf.predict(x_test)
                    acc = metrics.accuracy_score(y_test, y_pred)
                    print("Acuuracy: ", acc)
                    print(wine.feature_names)
                    print("Feature importance: ")
                    print(clf.feature_importances_)
                    if best_auc < acc:
                        best_auc = acc
print(best_auc)

gini best 2 5 5 0.3
Acuuracy:  0.8888888888888888
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.51621621 0.         0.         0.48378379 0.         0.
 0.        ]
gini best 2 5 10 0.3
Acuuracy:  0.8888888888888888
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.48378379 0.         0.51621621
 0.        ]
gini best 2 5 15 0.3
Acuuracy:  0.8888888888888888
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phen

Acuuracy:  0.9166666666666666
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.60294763 0.         0.         0.         0.         0.
 0.39705237]
entropy best 2 20 15 0.3
Acuuracy:  0.9166666666666666
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.60294763 0.         0.         0.         0.         0.
 0.39705237]
entropy best 5 5 5 0.3
Acuuracy:  0.9166666666666666
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins

entropy random 7 5 5 0.3
Acuuracy:  0.5833333333333334
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
entropy random 7 5 10 0.3
Acuuracy:  0.3888888888888889
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
entropy random 7 5 15 0.3
Acuuracy:  0.5277777777777778
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
entropy random 7 

In [23]:
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=11)
clf = DecisionTreeRegressor()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
mse = metrics.mean_squared_error(y_test, y_pred)
print("MSE: ", mse)
print(wine.feature_names)
print("Feature importance: ")
print(clf.feature_importances_)



MSE:  37.28941176470588
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[2.96516340e-02 1.66915174e-03 2.17809064e-03 3.71019500e-04
 3.39166872e-02 6.05305402e-01 6.08460917e-03 7.30335294e-02
 1.27378904e-03 9.53316383e-03 1.78216472e-02 7.04553642e-03
 2.12115740e-01]


In [24]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [25]:
greg = linear_model.LinearRegression()
greg.fit(x_train, y_train)
y_pred = greg.predict(x_test)
print(greg.coef_)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

[-9.62677805e-02  4.58403839e-02  1.68589207e-02  3.59545656e+00
 -1.90173156e+01  4.24296126e+00  1.31751330e-02 -1.38036743e+00
  3.03024557e-01 -1.15420503e-02 -8.87520457e-01  1.08290708e-02
 -5.25212073e-01]
Mean squared error: 26.94
