## [作業重點]
確保你了解隨機森林模型中每個超參數的意義，並觀察調整超參數對結果的影響

## 作業

1. 試著調整 RandomForestClassifier(...) 中的參數，並觀察是否會改變結果？
2. 改用其他資料集 (boston, wine)，並與回歸模型與決策樹的結果進行比較

In [1]:
from sklearn import datasets, metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [3]:
wine = datasets.load_wine()
x_train, x_test, y_train, y_test = train_test_split(wine.data, wine.target, test_size=0.2, random_state=11)
clf = RandomForestClassifier(n_estimators=20, max_depth=4)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acc = metrics.accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)

Accuracy:  0.9722222222222222


In [6]:
n_estimators = [1, 10, 40, 80, 100]
criterion = ['gini', 'entropy']
max_depth = [2,5,7]
min_samples_split= [5, 10, 20]
min_samples_leaf = [5, 10, 15]
min_weight_fraction_leaf=0.3
best_auc = 0
for a in range(len(n_estimators)):
    for b in range(len(criterion)):
        for c in range(len(max_depth)):
            for d in range(len(min_samples_split)):
                for e in range(len(min_samples_leaf)):
                    print(n_estimators[a],criterion[b],max_depth[c],min_samples_split[d],min_samples_leaf[e],min_weight_fraction_leaf)
                    clf = RandomForestClassifier(
                    n_estimators = n_estimators[f]
                    ,criterion = criterion[b]
                    ,max_depth = max_depth[c]
                    ,min_samples_split = min_samples_split[d]
                    ,min_samples_leaf = min_samples_leaf[e]
                    ,min_weight_fraction_leaf = min_weight_fraction_leaf)
                    clf.fit(x_train, y_train)
                    y_pred = clf.predict(x_test)
                    acc = metrics.accuracy_score(y_test, y_pred)
                    print("Acuuracy: ", acc)
                    print(wine.feature_names)
                    print("Feature importance: ")
                    print(clf.feature_importances_)
                    if best_auc < acc:
                        best_auc = acc
print(best_auc)

1 gini 2 5 5 0.3
Acuuracy:  0.9166666666666666
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.40572242 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.59427758]
1 gini 2 5 10 0.3
Acuuracy:  0.9166666666666666
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.44825385 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.55174615
 0.        ]
1 gini 2 5 15 0.3
Acuuracy:  0.6388888888888888
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'pr

10 gini 5 20 5 0.3
Acuuracy:  0.8055555555555556
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
10 gini 5 20 10 0.3
Acuuracy:  0.5277777777777778
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
10 gini 5 20 15 0.3
Acuuracy:  0.6111111111111112
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
10 gini 7 5 5 0.3
Acuuracy:  0.6944

40 gini 7 10 10 0.3
Acuuracy:  0.9166666666666666
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.48731569 0.
 0.51268431]
40 gini 7 10 15 0.3
Acuuracy:  0.5555555555555556
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
40 gini 7 20 5 0.3
Acuuracy:  0.8611111111111112
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature

Acuuracy:  0.7222222222222222
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.60781219 0.39218781 0.
 0.        ]
80 gini 7 20 15 0.3
Acuuracy:  0.8888888888888888
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.49779271 0.         0.50220729
 0.        ]
80 entropy 2 5 5 0.3
Acuuracy:  0.8055555555555556
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanin

Acuuracy:  0.7222222222222222
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.31412602
 0.         0.         0.         0.         0.68587398 0.
 0.        ]
100 gini 7 20 5 0.3
Acuuracy:  0.8611111111111112
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.56956294 0.         0.
 0.43043706]
100 gini 7 20 10 0.3
Acuuracy:  0.7222222222222222
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanin

In [13]:
from sklearn.ensemble import RandomForestRegressor
boston = datasets.load_boston()
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=11)
clf = RandomForestRegressor(n_estimators=40, max_depth=10)
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
mse = metrics.mean_squared_error(y_test, y_pred)
print("MSE: ", mse)

MSE:  18.958598975513116


In [8]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
greg = linear_model.LinearRegression()
greg.fit(x_train, y_train)
y_pred = greg.predict(x_test)
print(greg.coef_)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))

[-9.62677805e-02  4.58403839e-02  1.68589207e-02  3.59545656e+00
 -1.90173156e+01  4.24296126e+00  1.31751330e-02 -1.38036743e+00
  3.03024557e-01 -1.15420503e-02 -8.87520457e-01  1.08290708e-02
 -5.25212073e-01]
Mean squared error: 26.94


In [10]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
clf = DecisionTreeRegressor()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
mse = metrics.mean_squared_error(y_test, y_pred)
print("MSE: ", mse)
print(wine.feature_names)
print("Feature importance: ")
print(clf.feature_importances_)

MSE:  18.23450980392157
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Feature importance: 
[0.029692   0.00218824 0.00228042 0.00916002 0.03376901 0.60552404
 0.00637218 0.06373025 0.00160093 0.00832097 0.01770391 0.01844326
 0.20121477]
